version: '3.8'

services:
  findbot:
    build:
      dockerfile: ./Dockerfile
    container_name: findbot
    volumes:
      - ./testbackend:/app
    environment:
      - PORT=80
    networks:
      - findbot_network
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 500M

networks:
  findbot_network:
    driver: bridge
