version: '3.8'

services:
  findbot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: findbot
    volumes:
      - ./testbackend:/app
    environment:
      - PORT=80
    networks:
      - findbot_network
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 500M
    command: /opt/conda/bin/conda run -n findbot /bin/bash -c python /app/test.py

networks:
  findbot_network:
    driver: bridge

